<?
$aMenuLinks = Array(
	Array(
		"checkReq", 
		"/local/modules/smoservice/smoservice/templates/index.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"createOrder", 
		"/local/modules/smoservice/templates/createOrder.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"checkOrder", 
		"/local/modules/smoservice/templates/checkOrder.php", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"result", 
		"/local/modules/smoservice/templates/result.php", 
		Array(), 
		Array(), 
		"" 
	)
);
?>